### ISSUE TITLE
How to use this project, do you copy the code in readme.md in vscode?

### ISSUE THREAD

**Issue by zy-187** [bigcode-project/starcoder#11]
After installing the dependent library, how to use it

**Comment by lvwerra** [comment]
If you just want to use the model in VScode you can install the plugin from the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=HuggingFace.huggingface-vscode) or if you would like to work on the extension itself have a look at the [repo](https://github.com/huggingface/huggingface-vscode).
