### ISSUE TITLE
Questions about tokenizer

### ISSUE THREAD

**Issue by Dmm2584v** [bigcode-project/starcoder#117]
I have a few questions about the tokenizer trained in the project.

1. What and how much data is the tokenizer vocabulary trained with?
2. For code vocabulary, do you train from scratch or do you do incremental learning?
3. Have you verified the validity of the vocabulary after its modification?

**Comment by cakiki** [comment]
Hi there!

1 - The tokenizer was trained on the following subset of the stack: https://huggingface.co/datasets/bigcode/the-stack-march-sample-special-tokens-stripped
2 - The tokenizer was trained from scratch. The training script can be found here: https://github.com/bigcode-project/bigcode-tokenizer/blob/main/train_bpe_tokenizer.py
3 - I'm not exactly sure what you mean with validity in this context, but we did run a few manual spot checks to make sure the tokenizer was behaving properly.
