### ISSUE TITLE
Using the model for code reviews in pull requests

### ISSUE THREAD

**Issue by clime** [bigcode-project/starcoder#19]
Hello,

was the model also trained on pull/merge requests? Is it reasonable to try to use for code reviews?

Thanks!

**Comment by loubnabnl** [comment]
Hello, the model is not trained on code reviews, but it was trained github commits and diffs as well as conversations from issues and pull requests, which might help with this task.

**Comment by clime** [comment]
Yes, that helps. Thanks!
