### ISSUE TITLE
VS Code plugin is breaking the completion

### ISSUE THREAD

**Issue by averkij** [bigcode-project/starcoder#2]
Hello! Thank you for your work.

I've encountered a strange behavior using a VS Code plugin (HF autocompletion). Sometimes it breaks the completion and adding it from the middle, like this:

![](https://i.imgur.com/7HIPYiE.png)

![](https://i.imgur.com/USW0462.png)

Looks like there are some issues with plugin.

_VS Code version 1.79.0-insider_

**Comment by lvwerra** [comment]
Can you try again if the issue persists after the fix in https://github.com/huggingface/huggingface-vscode/pull/10?

**Comment by averkij** [comment]
Looks good now. Thank you.
