### ISSUE TITLE
data preprocess code

### ISSUE THREAD

**Issue by ryh95** [bigcode-project/starcoder#20]
From the hugging face [blog](https://huggingface.co/blog/starcoder)
all code for data preprocessing will be released

Where are these codes?
Could you provide a link?

Thanks!

**Comment by slacklife** [comment]
We also have the same problem.

In addition, we also found out that
the code attribution tool is [offline](https://huggingface.co/spaces/bigcode/starcoder-search);
the code to train from scratch and  evaluations harness for code models cannot be found.

Can you provide the links?
Thank you !

**Comment by ryh95** [comment]
Hi @slacklife 
I think the evaluation codes are at https://github.com/bigcode-project/bigcode-evaluation-harness
the code to train from scratch maybe this one https://github.com/bigcode-project/Megatron-LM

**Comment by SivilTaram** [comment]
@ryh95 Yes you're right! Good job!

**Comment by loubnabnl** [comment]
The data preprocessing code can be found at [bigcode-dataset](https://github.com/bigcode-project/bigcode-dataset). The preprocessed dataset is available at [StarCoderData](https://huggingface.co/datasets/bigcode/starcoderdata).
The evaluation and training code are in the links provided by @ryh95.

**Comment by slacklife** [comment]
Very good!
