### ISSUE TITLE
Is it possible to continue training from the last lora checkpoint?

### ISSUE THREAD

**Issue by edwardelric1202** [bigcode-project/starcoder#21]
Hi, I wonder that if I can continue finetune this model from the last lora checkpoint if I interrupted training process?

**Comment by brainwavecoder9** [comment]
With PyTorch trainer you can replace 
`trainer.train()`

with 
`trainer.train(resume_from_checkpoint=<PATH>)` _e.g. "checkpoint-1234"_
or 
`trainer.train(resume_from_checkpoint = True)`

[More info from HF docs](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.Trainer.train.resume_from_checkpoint)
