### ISSUE TITLE
`bfloat16` / `float16` StarCoder keeps producing `<|endoftext|>` for HumanEval inputs in greedy decoding

### ISSUE THREAD

**Issue by ganler** [bigcode-project/starcoder#23]
Thanks for open-sourcing this amazing work. However, I tried to starcoder with half-precision and greedy decoing but it simply produces `<|endoftext|>` for the majority of problems in HumanEval. However, from the paper, the pass@1 is pretty good (33.6 / 40.8). I am curious if it is expected or if it is because I did not use it in the right way. (sorry the A6000 we had cannot load the full-precision version...)  Thanks!

A quick repro:

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

checkpoint = "bigcode/starcoder"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForCausalLM.from_pretrained(
    checkpoint, torch_dtype=torch.bfloat16
).cuda()

text = R'''from typing import List


def separate_paren_groups(paren_string: str) -> List[str]:
    """ Input to this function is a string containing multiple groups of nested parentheses. Your goal is to
    separate those group into separate strings and return the list of those.
    Separate groups are balanced (each open brace is properly closed) and not nested within each other
    Ignore any spaces in the input string.
    >>> separate_paren_groups('( ) (( )) (( )( ))')
    ['()', '(())', '(()())']
    """
'''

inputs = tokenizer.encode(text, return_tensors="pt").cuda()
outputs = model.generate(inputs, max_new_tokens=512, do_sample=False, temperature=0) # greedy
print(tokenizer.decode(outputs[0]))
```

When setting a higher temperature, it can produce something different but sometimes invalid:

0.8

![image](https://github.com/bigcode-project/starcoder/assets/38074777/24dd65b9-c914-4402-909e-f1aca91e1198)

0.2

![image](https://github.com/bigcode-project/starcoder/assets/38074777/71f87b00-cf11-4627-a276-0f70edea2688)

0.1

![image](https://github.com/bigcode-project/starcoder/assets/38074777/eb166597-cf4a-4425-a9cd-0f741288ed3d)

**Comment by rookielyb** [comment]
hello, I have the same problem
this is my code

企业微信截图_d75ee79f-5d8b-47b1-8dd2-90f08aedbf16.png
I predicted 10 times and didn't get one correct result

企业微信截图_0fdde452-8bfa-4f0e-ab56-1e434709f631.png
But I try to use your api, can get the correct result

企业微信截图_d92508a3-b65c-4886-a2a7-da07b5b8e7f4.png

企业微信截图_5fe67b3b-5dab-48c4-9f90-124ed0015831.png
Why is this? I'm having a hard time achieving your results in human eval.
Hope to get your reply!

**Comment by rookielyb** [comment]
hello, I have the same problem
this is my code

<img width="854" alt="企业微信截图_d75ee79f-5d8b-47b1-8dd2-90f08aedbf16" src="https://github.com/bigcode-project/starcoder/assets/50746135/f4b95214-9b3f-4d87-9bc4-8996d418de74">
I predicted 10 times and didn't get one correct result

<img width="698" alt="企业微信截图_0fdde452-8bfa-4f0e-ab56-1e434709f631" src="https://github.com/bigcode-project/starcoder/assets/50746135/ceb45460-879b-4098-90a0-a9288f533cf5">
But I try to use your api, can get the correct result

<img width="1178" alt="企业微信截图_d92508a3-b65c-4886-a2a7-da07b5b8e7f4" src="https://github.com/bigcode-project/starcoder/assets/50746135/c3bd9f70-2db3-499b-bc46-5a45abc581de">

<img width="583" alt="企业微信截图_5fe67b3b-5dab-48c4-9f90-124ed0015831" src="https://github.com/bigcode-project/starcoder/assets/50746135/3868f728-4119-4108-a776-65b9c78e5f26">
Why is this? I'm having a hard time achieving your results in human eval.
Hope to get your reply!

**Comment by jithurjacob** [comment]
Facing the same issue, and getting good results on HF inference API but not locally.

**Comment by loubnabnl** [comment]
We have evaluated the model on HumanEval using the [evaluation harness](https://github.com/bigcode-project/bigcode-evaluation-harness), Bf16 and Fp16 give close scores to full precision. You can run the evaluation yourself to check the numbers using the parameters we specify in the [paper](https://arxiv.org/abs/2305.06161) (for example we use top-p sampling instead of greedy decoding and we strip the prompt before generation + do post-processing to remove `eos_token` and any text after some stop-tokens). 

As for the [playground](https://huggingface.co/spaces/bigcode/bigcode-playground), it calls the inference [endpoint](https://huggingface.co/spaces/bigcode/bigcode-playground/blob/2009abb380464f89aba1603069e720f031735cce/app.py#L13) to generate code which is equivalent to doing `model.generate` just make sure you use the same parameters as the playground. It uses random sampling so it's normal to not get the same result as the playground:
<img width="677" alt="image" src="https://github.com/bigcode-project/starcoder/assets/44069155/1e1dd452-56bb-4297-901a-fae36796c5a7">

**Comment by ganler** [comment]
@loubnabnl Thanks for the reply. After some in-depth debugging I found starcoder tend to work better given a higher temperature and seem not to fit situations for greedy decoding and a very low temperature such as 0.1. I am curious if it is unexpected to run StarCoder under a greedy decoding setting for benchmarking as the results are not quite reasonable ... because for many other models I tried they tend to even perform better pass@1 than that from random sampling. Thanks!

**Comment by ganler** [comment]
In addition, in the evaluation did you use autoaggressive generation? The playground code seems to use in-filling. I had the same experience with SantaCoder where the AR does not seem to work reasonably but the in-filling mode works fine.

**Comment by ganler** [comment]
Update: I finally made StarCoder output reasonable code by following https://huggingface.co/spaces/bigcode/bigcode-playground/blob/2009abb380464f89aba1603069e720f031735cce/app.py

and replicate a pretty nice pass@1:

![image](https://github.com/bigcode-project/starcoder/assets/38074777/64175c24-87b3-4502-8b13-501378ece64e)

The detailed usage is listed here: https://github.com/evalplus/evalplus/blob/694528a1e933ea1d12559f41cebac1a6ad1100dc/codegen/model.py#L494

- Use infilling
- Set `repetition_penalty=1`
- let `temperature = 1e-2` instead of 0

Note that maybe not all of them are necessary to make "greedy" decoding work but that is the configuration I tried to be feasible. Thanks for creating the great bigcode project!

**Comment by loubnabnl** [comment]
It's great that it works. Btw I run HumanEval on StarCoder with greedy and the score is pretty high by default (this is left-to-right no infilling, the playground doesn't use infilling by default unless you add the `<FILL_HERE>` token to your prompt).

CLI in [evaluation harness:](https://github.com/bigcode-project/bigcode-evaluation-harness)
```
accelerate launch  main.py   --model bigcode/starcoder   --max_length_generation 512  --tasks humaneval   --n
_samples 1   --batch_size 1   --temperature 0   --do_sample False   --precision bf16   --allow_code_execution   --use_auth_token       
```
Result:
```python                                                                                                                         
{
  "humaneval": {
    "pass@1": 0.3475609756097561
  },
  "config": {
    "model": "bigcode/starcoder",
    "temperature": 0.0,
    "n_samples": 1
  }
}
```
