### ISSUE TITLE
Could model definition code be open sourced?

### ISSUE THREAD

**Issue by ZJXNEFU** [bigcode-project/starcoder#24]
I really want to know how multi-query attention and Fill-in-the-Middle combined with raw model.

**Comment by loubnabnl** [comment]
The architecture of the model is integrated in `transformers` [here](https://github.com/huggingface/transformers/tree/main/src/transformers/models/gpt_bigcode) so you can find MQA implementation. Fill-in-the-middle is a data transformation we apply before the pre-training, you can find the implementation in our [Megatron-LM codebase ](https://github.com/bigcode-project/Megatron-LM/blob/1a7d54bc3f897d068eb78c5b0874d4d69c9af5ea/megatron/data/gpt_dataset.py#L302) or this [repo](https://github.com/loubnabnl/santacoder-finetuning/blob/13b69333fe60d0201c35f40ca0c5a8bfce104f80/train.py#L152).

**Comment by ZJXNEFU** [comment]
ok, thanks a lot!
