### ISSUE TITLE
Model weights for Megatron model

### ISSUE THREAD

**Issue by edward-io** [bigcode-project/starcoder#25]
Is it possible to open source the weights and config before the conversion to Huggingface, similar to [santacoder-megatron](https://huggingface.co/bigcode/santacoder-megatron)? Thanks!

**Comment by loubnabnl** [comment]
The megatron checkpoints are now available at [starcoder-megatron](https://huggingface.co/bigcode/starcoder-megatron) and [starcodebase-megatron](https://huggingface.co/bigcode/starcoderbase-megatron)

**Comment by edward-io** [comment]
Thank you!

**Comment by senxiangms** [comment]
@edward-io , do you know how to load the starcoder-megatron checkpoints? they are sharded, and has no index.json file.
