### ISSUE TITLE
Are there plans to support JetBrains plugins like vscode for starcoder?

### ISSUE THREAD

**Issue by aphrodite1028** [bigcode-project/starcoder#26]

**Comment by aphrodite1028** [comment]
> There is an opensource plugin for CoPilot that could be converted. https://github.com/pannous/jini-plugin

thanks for your reply, i will try it.

**Comment by alifanov** [comment]
@aphrodite1028 was it successful?

**Comment by aphrodite1028** [comment]
> @aphrodite1028 was it successful?

yes, it works for me, but needs some development, thanks

**Comment by alifanov** [comment]
> > @aphrodite1028 was it successful?
> 
> yes, it works for me, but needs some development, thanks

could you provider some guide or how to for implementing it?
