### ISSUE TITLE
OOM on T4 inference 

### ISSUE THREAD

**Issue by hellangleZ** [bigcode-project/starcoder#28]
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForCausalLM.from_pretrained(checkpoint).to(device)

Does anyone could help me to resolve the problem ,T4 has almost 15G GPU memory

![image](https://github.com/bigcode-project/starcoder/assets/15274284/bf1933a1-153b-4798-9220-e59f1234c264)

And if I use:

with torch.device(device):
    model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16)

There is another issue

![image](https://github.com/bigcode-project/starcoder/assets/15274284/b733225d-2c55-44d6-826b-609347a8cba8)

**Comment by loubnabnl** [comment]
StarCoder will probably not fit on a T4, we added some hardware requirements section [here](https://github.com/bigcode-project/starcoder#inference-hardware-requirements), 8bit mode takes almost 16GB of RAM.
