### ISSUE TITLE
Starcoder model integration in Huggingchat

### ISSUE THREAD

**Issue by kumarselvakumaran-sentient** [bigcode-project/starcoder#30]
Hello @ArmelRandy @lewtun , and other authors. In the readme file, I found that the "chat" Iink leads me to the Huggingchat page, but i can't seem to find any presence of Starcoder on the Huggingchat page. 

If Starcoder has already been integrated into Huggingchat, would you mind directing me to where I can find the integration. 

Thank you.

**Comment by lewtun** [comment]
Hello @kumarselvakumaran-sentient we were hosting the prompted StarCoder model in HuggingChat, but have removed it for now since it wasn't giving reliably good answers. We're exploring whether to include StarChat Alpha (or an improved version), so stay tuned!
