### ISSUE TITLE
How to disable "wandb" while running finetune.py

### ISSUE THREAD

**Issue by leemgs** [bigcode-project/starcoder#37]
Hi there. I am wondering how to disable the functionality of wanddb, when running finetune.py. 
Is it possible to do this by executing the "**$wandb offline**" command?

Or are there any options instead of "**report_to="wandb**"" when running Starcoder's finetune.py file?
- https://github.com/bigcode-project/starcoder/blob/main/finetune/finetune.py#L285

**Comment by amwork2020** [comment]
report_to=[]  is ok

**Comment by ArmelRandy** [comment]
You can remove that argument in `Trainer`, or change where you want to report your logs, e.g.` report_to=["tensorboard"]`. In this case you will have to make sure that it is properly installed.

**Comment by ywen666** [comment]
I did something like `WANDB_MODE=disabled python finetune.py --args` when doing a testing run.

**Comment by CEfanmin** [comment]
> You can remove that argument in `Trainer`, or change where you want to report your logs, e.g.` report_to=["tensorboard"]`. In this case you will have to make sure that it is properly installed.

remove is not working
