### ISSUE TITLE
only small amount  coming as output.

### ISSUE THREAD

**Issue by EngOMAR2030** [bigcode-project/starcoder#39]
I run the model and when running the model this message appears:
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Input length of input_ids is 21, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

and the output is only small characters not so much of words like the demo of the model page in the huggingface website.

**Comment by nandovallec** [comment]
+1, I've tried setting the pad token to different values and force output with `min_length` but the output is just random noise.

**Comment by EngOMAR2030** [comment]
Done that and worked.. thank you.
