### ISSUE TITLE
Obtaining different results when run locally

### ISSUE THREAD

**Issue by nandovallec** [bigcode-project/starcoder#40]
Hello everyone,
I'm trying to use StarcoderBase model locally to generate a docstring. The version in the bigcode-playground works perfectly, but when using the model locally I obtain really different results. 

Since the app on the playground doesn't include if there are extra configurations for tokenizer or the model, I wondered if there is something that I was doing or maybe there is an actual problem when running the local model. 
The example used in the playground:
`\n\n/**\n@description <FILL_HERE>\n*/\npublic static int bitcount(int n) {\nint count = 0;\nwhile (n != 0) {\n    n = (n ^ (n - 1));\n        count++;\n}\nreturn count;\n}\n`
My code so far is quite basic:
```
tokenizer = AutoTokenizer.from_pretrained(model_dir + model_name, local_files_only =True)
model = AutoModelForCausalLM.from_pretrained(model_dir + model_name, local_files_only=True, device_map="auto", trust_remote_code=True)
text = '<fim-prefix>\n\n/**\n@description <fim-suffix>\n*/\npublic static int bitcount(int n) {\nint count = 0;\nwhile (n != 0) {\n    n = (n ^ (n - 1));\n        count++;\n}\nreturn count;\n}\n<fim-middle>'

input_ids = tokenizer(text, return_tensors="pt", return_token_type_ids=False).input_ids.to('cuda')

generated_ids = model.generate(
input_ids, num_return_sequences=5,
do_sample=True, top_p= 0.9, #pad_token_id=tokenizer.pad_token_id,
temperature=0.3, max_new_tokens=128,
    repetition_penalty=1.2
)
```

I mainly get empty outputs or random HTML noise. Maybe someone has any advice or way to check that the model is up to date.

Best regards.

**Comment by loubnabnl** [comment]
Hello, you are using the wrong FIM tokens, StarCoder uses underscores instead of dashes so can you try again with:
```python
text = '<fim_prefix>\n\n/**\n@description <fim_suffix>\n*/\npublic static int bitcount(int n) {\nint count = 0;\nwhile (n != 0) {\n    n = (n ^ (n - 1));\n        count++;\n}\nreturn count;\n}\n<fim_middle>'
```
The API endpoint in the playground doesn't add any extra configs to the tokenizer and uses tokens with underscores [here](https://huggingface.co/spaces/bigcode/bigcode-playground/blob/02913d9b050e7689a58797ea8cceabf72783fd29/app.py#L16).

**Comment by nandovallec** [comment]
You are absolutely right. I came from the SantaCoder model where the mask used dashes.
Thank you for taking the time.
