### ISSUE TITLE
Fine-tuning on other programming languages than Python

### ISSUE THREAD

**Issue by realfenston** [bigcode-project/starcoder#42]
Hello,

It is really exciting to see your work! May I know if the codes for fine-tuning on other programming languages will be released in the near future?  Up to now, the only version that could be found online is about Python though.

Thanks in advance.

**Comment by realfenston** [comment]
By the way, it is because our team is more often working with Gaming design languages like C-sharp.

**Comment by loubnabnl** [comment]
Hi, we used the same pre-training framework [Megatron-LM](https://github.com/bigcode-project/Megatron-LM) to do the fine-tuning on the Python dataset, that you can use with any other dataset, or use the code provided in this repository, with the dataset of your choice.

**Comment by realfenston** [comment]
Thanks a lot for the update. I am not familiar with coed implementations in Megatron-LM, however. May I know with which file(s) should I follow to understand the fine-tuning logic?

Thanks in advance!

**Comment by realfenston** [comment]
Hi,

I am looking into the examples directory and will update this ticket once it has been executed properly. Thanks.

**Comment by realfenston** [comment]
Hello, my fine-tuning snippet is working now and you may close this ticket. Thank you for the help!
