### ISSUE TITLE
minimum hardware

### ISSUE THREAD

**Issue by galfaroi** [bigcode-project/starcoder#6]
What is the minimum hardware someone has run this? I have 32 CPU ram and a 4090 GPU (24 GB) and no luck so far...

**Comment by loubnabnl** [comment]
you should be able to load the model under 20GB of GPU RAM with `load_in_8bit`, otherwise fp16 or bf16 take around 30GB (without ~60GB).

```
!pip install transformers accelerate bitsandbytes
!huggingface-cli login
```
```python
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bigcode/starcoder")
model = AutoModelForCausalLM.from_pretrained("bigcode/starcoder", device_map="auto", load_in_8bit=True)
print(f"Memory footprint: {model.get_memory_footprint() / 1e6:.2f} MB")
````
````
Memory footprint: 15939.61 MB
````

**Comment by galfaroi** [comment]
It works... thanks! 
So far the same inference output compared to the version with 16fp on the Huggingface space, have you run quantization benchmarks?

How suitable is to fine tunning with 8 bit?

**Comment by aseok** [comment]
How to run inference in multiple gpus? What are instructions?

**Comment by loubnabnl** [comment]
If you want to shard the model on multiple GPUs then `device_map="auto"` takes care of it, you can define max memory to use per GPU using code like this:
```python
# make sure you have accelerate installed
from transformers import AutoModelForCausalLM
import torch

def get_gpus_max_memory(max_memory):
    max_memory = {i: max_memory for i in range(torch.cuda.device_count())}
    return max_memory

# for example for a max use of 10GB per GPU
# for fp16 replace with  `load_in_8bit=True` with   `torch_dtype=torch.float16`
model = AutoModelForCausalLM.from_pretrained(
    "bigcode/starcoder", 
    device_map="auto", 
    load_in_8bit=True,
    max_memory=get_gpus_max_memory("10GB"),
)
```
if you want to generate multiple samples using data parallelism you can build a dataloader and wrap it  with `accelerate` like it's done in our evaluation harness [here](https://github.com/bigcode-project/bigcode-evaluation-harness/blob/04b34934e101bdcfc4a28b31ac0643176abc9aaf/lm_eval/generation.py#L84).

As for quantization benchmarks there are some ongoing experiments [here](https://github.com/mayank31398/GPTQ-for-SantaCoder) by @mayank31398

**Comment by Avik-creator** [comment]
Just asking which model should I download for using it in my M1 MacBook Air? @loubnabnl
