### ISSUE TITLE
Lora finetuning generating <|endoftext|>

### ISSUE THREAD

**Issue by dittops** [bigcode-project/starcoder#82]
I have finetuned the `bigcode/starcoder` with Lora. I'm using finetune.py with the below command.

`python finetune/finetune.py  --model_path bigcode/starcoder --dataset_name /root/bud-conv/data-preprocess/data/dummy-instruction.json --size_valid_set 10 --input_column_name instruction --output_column_name output --output_dir output/coder-lora-indentity-v1 --save_freq 50`

But when I load the resultant adaptor, the model only generates <|endoftext|> while using the instruction used for the Lora fine-tune data. Any thought on what could be the issue?

**Comment by mathav95raj** [comment]
What was the hardware configuration you have used for fine tuning?

**Comment by ArmelRandy** [comment]
It is pretty difficult to answer to your issue without context. Have you recorded to loss during the training and checked if it the loss was decreasing? Did you merge your model adapters with the provided code? What code did you use for the generation?

**Comment by dittops** [comment]
I was using A100 80GB. Yes, the loss was decreasing. I haven't merged the code but loaded the Lora adaptor separately. 

But I was able to resolve it by creating a simple training script. Not exactly sure if the issue was with the script or the environment.

**Comment by bigmancomeon** [comment]
Do you use one A100 80GB gpu to finetune the model ,it can be work?

**Comment by bigmancomeon** [comment]
> Do you use one A100 80GB gpu to finetune the model ,it can be work?

**Comment by ArmelRandy** [comment]
If you use LoRa and you fine-tune in 8bits, you should be able to do it on a single A100 80G.

**Comment by bigmancomeon** [comment]
> If you use LoRa and you fine-tune in 8bits, you should be able to do it on a single A100 80G.

I use 6  Tesla T4(15GB)  gpu,this is tatol 6*15=90GB,but finetune is failed,showing gpu out of memory.Have you used distributed finetune?
