### ISSUE TITLE
Running startcoder locally on my machine

### ISSUE THREAD

**Issue by moshere** [bigcode-project/starcoder#95]
Hi,
Where I can find instructions to run starcoder on my local machine (i.e. desktop with GPU or AWS EC2 machine with GPU)?
Thank you

**Comment by ArmelRandy** [comment]
Hi. There are some alternatives that you can explore if you want to run starcoder locally 
- [StarCoder in C++](https://github.com/bigcode-project/starcoder.cpp)
- [The VSCode extension](https://marketplace.visualstudio.com/items?itemName=HuggingFace.huggingface-vscode)
- [A resource about using models of the hub locally](https://discuss.huggingface.co/t/run-models-on-a-desktop-computer/31125) (Refer to the model card)
- [This can also be of interest](https://discuss.huggingface.co/t/best-practice-for-using-transformers-on-gpu-on-ec2/3440)

**Comment by GurpreetSingh97** [comment]
This would help: 

https://huggingface.co/docs/transformers/installation#offline-mode



```

from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoToklsenizer.from_pretrained("HuggingFaceH4/starchat-alpha")
model = AutoModelForCausalLM.from_pretrained("HuggingFaceH4/starchat-alpha")

*#mention the directory where you want to save the checkpoint
*tokenizer.save_pretrained("/home/ec2-user/starCoderCheckpointLocal")
model.save_pretrained("/home/ec2-user/starCoderCheckpointLocal")

*#these commands check if the model is working offline using the local directory
*tokenizer = AutoTokenizer.from_pretrained("/home/ec2-user/starCoderCheckpointLocal")
model = AutoModelForCausalLM.from_pretrained("/home/ec2-user/starCoderCheckpointLocal")
```
