### ISSUE TITLE
how to use infilling feature in starcoder

### ISSUE THREAD

**Issue by jemmyshin** [bigcode-project/starcoder#99]
From the paper, I see starcoder supports infilling, but I didn't see how this was implemented in huggingface API.
Is there any API or way we can use this feature?

**Comment by ArmelRandy** [comment]
Hi. If you are referring to fill-in-the-middle, you can play with it on the [bigcode-playground](https://huggingface.co/spaces/bigcode/bigcode-playground). You just have to provide the model with `Code before <FILL_HERE> Code after`. It will complete the implementation in accordance with `Code before` and `Code after`. For example, if you give this to the model
```
def fibonacci(n):
  if n == 0 :
     return 1
  elif n == 1 :
     return 1
  else :
     a = 0
     b = 1
     <FILL_HERE>
     return b
```
It will return this 
```
def fibonacci(n):
  if n == 0 :
     return 1
  elif n == 1 :
     return 1
  else :
     a = 0
     b = 1
     for i in range (2,n+1) :
        c=a +b 
        a=b  
        b=c  
     return b
```

**Comment by michaelmior** [comment]
Note that if you want to implement this yourself, instead of "before <FILL_HERE> after", your prompt should actually be `<fim_prefix>before <fim_suffix> after<fim_middle>`. Look at the [code for the space](https://huggingface.co/spaces/bigcode/bigcode-playground/blob/main/app.py) for details.

**Comment by NightMachinery** [comment]
Is there any cloud API that supports fill-in-the-middle? I could not find Starcoder on OpenRouter.
